#!/bin/zsh
. "$(dirname "$0")/common.sh"

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=$(git hash-object -t tree /dev/null)
fi

# Redirect output to stderr.
exec 1>&2

if [[ ("${FORCE_COMMIT:-false}" != "true") ]];
then
  for f in $(git diff --cached --name-only --diff-filter=M -z $against);
  do
    if [[ "$f" =~ ".*configs/dev/.*\.yml$" ]]; then
      cat <<\EOF
Error: Attempt to commit a dev config file
Aborting commit
EOF
      exit 1
    fi
  done
fi

for f in $(git diff --cached --name-only --diff-filter=A -z $against);
do
  if [[ "$f" =~ ".*=" ]]; then
    cat <<\EOF
Error: Attempt to commit a file with name ending with '='.
Aborting commit
EOF
    exit 1
  fi
  if [[ "$f" =~ ".*\\\\" ]]; then
    cat <<\EOF
Error: Attempt to commit a file with name ending with '\\'.
Aborting commit
EOF
    exit 1
  fi
done

if [[ ("${FORCE_COMMIT:-false}" != "true") ]];
then
  for i in $(git status --short | grep -E '(^A)|(^M)' | sed 's/...//' | grep -E '_enc\.|_enc$');
  do
    if [[ !(`file $i` =~ ".*GPG.*") ]]; then
      cat <<\EOF
Please encrypt protected files (*_enc*)
Aborting commit
EOF
      exit 1
    fi
  done
fi
