export EDITOR=nvim
export CC=clang
export TZ=Europe/Paris
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export WORKON_HOME=$HOME/.virtualenvs
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export GOPRIVATE=github.com/t-dx/*,github.com/taurusgroup/*
export PYTHONPATH=$HOME/Documents/Prog/Perso/pytoolkit:$PYTHONPATH
export PYTHONBREAKPOINT=ipdb.set_trace
export PYENV_ROOT="$HOME/.pyenv"
export AWS_ASSUME_ROLE_TTL=4h
export AWS_CHAINED_SESSION_TOKEN_TTL=1h
export AWS_FEDERATION_TOKEN_TTL=4h
export AWS_SESSION_TOKEN_TTL=4h
export AWS_PAGER=
export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
export CPPFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
export LDFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
export ZSH_HIGHLIGHT_MAXLENGTH=60     # For perf on text paste
export GITHUD_DEBUG=TRUE
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export SHELL_USER=gbataille
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=true
export BUF_USER=gbataille
export ALGORAND_HOME=$HOME/Documents/Prog/Cryptos/AlgoNode
export ALGORAND_DATA=$ALGORAND_HOME/testnetdata
# RUST
export RUST_BACKTRACE=1
