[user]
name = "Grégory Bataille"
email = "gregory.bataille@lightframe.tech"
[signing]
behavior = "own"
backend = "gpg"
key = "16E3480ED00E3E09C7551C25CBD61BDEF9DB4581"

[ui]
default-command = "log"
merge-editor = "vimdiff"
diff-editor = ":builtin"
conflict-marker-style = "snapshot"

[merge-tools.vimdiff]
program = "nvim"

[git]
subprocess = true
push-new-bookmarks = true
